// <auto-generated />
using System;
using MedicalAppointmentSystem.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicalAppointmentSystem.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260513055608_AddNotifications")]
    partial class AddNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MedicalAppointmentSystem.Domain.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeclineReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("DoctorComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<int>("MedicalServiceId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("HospitalId");

                    b.HasIndex("MedicalServiceId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("MedicalAppointmentSystem.Domain.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HospitalId = 1,
                            Name = "Cardiology"
                        },
                        new
                        {
                            Id = 2,
                            HospitalId = 1,
                            Name = "Dermatology"
                        },
                        new
                        {
                            Id = 3,
                            HospitalId = 2,
                            Name = "Neurology"
                        },
                        new
                        {
                            Id = 4,
                            HospitalId = 2,
                            Name = "Narcology"
                        });
                });

            modelBuilder.Entity("MedicalAppointmentSystem.Domain.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<string>("IDNP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("HospitalId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Email = "elena.moraru@clinic.md",
                            FirstName = "Elena",
                            HospitalId = 1,
                            IDNP = "1980000000001",
                            LastName = "Moraru",
                            Password = "1234",
                            PhoneNumber = "069111111",
                            Specialization = "Cardiologist"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            Email = "victor.ciobanu@clinic.md",
                            FirstName = "Victor",
                            HospitalId = 1,
                            IDNP = "1985000000002",
                            LastName = "Ciobanu",
                            Password = "1234",
                            PhoneNumber = "069222222",
                            Specialization = "Dermatologist"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            Email = "maria.lungu@clinic.md",
                            FirstName = "Maria",
                            HospitalId = 2,
                            IDNP = "1990000000003",
                            LastName = "Lungu",
                            Password = "1234",
                            PhoneNumber = "069333333",
                            Specialization = "Neurologist"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 4,
                            Email = "andrei.munteanu@clinic.md",
                            FirstName = "Andrei",
                            HospitalId = 2,
                            IDNP = "1988000000004",
                            LastName = "Munteanu",
                            Password = "1234",
                            PhoneNumber = "069444444",
                            Specialization = "Narcologist"
                        });
                });

            modelBuilder.Entity("MedicalAppointmentSystem.Domain.Models.Hospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hospitals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Str. Nicolae Testemitanu 29, Chisinau",
                            Description = "Spital public cu mai multe sectii medicale.",
                            Name = "Spitalul Clinic Republican",
                            PhoneNumber = "022000001"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Str. Andrei Doga 24, Chisinau",
                            Description = "Clinica privata cu servicii medicale moderne.",
                            Name = "Medpark International Hospital",
                            PhoneNumber = "022000002"
                        });
                });

            modelBuilder.Entity("MedicalAppointmentSystem.Domain.Models.MedicalService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("MedicalServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Description = "Heart and blood pressure consultation.",
                            DurationMinutes = 45,
                            Name = "Cardiology Consultation",
                            Price = 400m
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Description = "Electrocardiogram investigation for heart activity.",
                            DurationMinutes = 20,
                            Name = "ECG Investigation",
                            Price = 250m
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 2,
                            Description = "Skin examination and treatment recommendations.",
                            DurationMinutes = 40,
                            Name = "Dermatology Consultation",
                            Price = 350m
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 3,
                            Description = "Consultation for nervous system problems.",
                            DurationMinutes = 50,
                            Name = "Neurology Consultation",
                            Price = 450m
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 4,
                            Description = "Consultation for addiction-related medical issues.",
                            DurationMinutes = 45,
                            Name = "Narcology Consultation",
                            Price = 300m
                        });
                });

            modelBuilder.Entity("MedicalAppointmentSystem.Domain.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("PatientId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("MedicalAppointmentSystem.Domain.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDNP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalCardFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2001, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ana.popescu@example.com",
                            FirstName = "Ana",
                            IDNP = "2001000000001",
                            LastName = "Popescu",
                            Password = "1234",
                            PhoneNumber = "060000001"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1998, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ion.rusu@example.com",
                            FirstName = "Ion",
                            IDNP = "1998000000002",
                            LastName = "Rusu",
                            Password = "1234",
                            PhoneNumber = "060000002"
                        });
                });

            modelBuilder.Entity("MedicalAppointmentSystem.Domain.Models.Appointment", b =>
                {
                    b.HasOne("MedicalAppointmentSystem.Domain.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MedicalAppointmentSystem.Domain.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MedicalAppointmentSystem.Domain.Models.Hospital", "Hospital")
                        .WithMany()
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MedicalAppointmentSystem.Domain.Models.MedicalService", "MedicalService")
                        .WithMany("Appointments")
                        .HasForeignKey("MedicalServiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MedicalAppointmentSystem.Domain.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Doctor");

                    b.Navigation("Hospital");

                    b.Navigation("MedicalService");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MedicalAppointmentSystem.Domain.Models.Department", b =>
                {
                    b.HasOne("MedicalAppointmentSystem.Domain.Models.Hospital", "Hospital")
                        .WithMany("Departments")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("MedicalAppointmentSystem.Domain.Models.Doctor", b =>
                {
                    b.HasOne("MedicalAppointmentSystem.Domain.Models.Department", "Department")
                        .WithMany("Doctors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MedicalAppointmentSystem.Domain.Models.Hospital", "Hospital")
                        .WithMany()
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("MedicalAppointmentSystem.Domain.Models.MedicalService", b =>
                {
                    b.HasOne("MedicalAppointmentSystem.Domain.Models.Department", "Department")
                        .WithMany("MedicalServices")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MedicalAppointmentSystem.Domain.Models.Notification", b =>
                {
                    b.HasOne("MedicalAppointmentSystem.Domain.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MedicalAppointmentSystem.Domain.Models.Patient", "Patient")
                        .WithMany("Notifications")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MedicalAppointmentSystem.Domain.Models.Department", b =>
                {
                    b.Navigation("Doctors");

                    b.Navigation("MedicalServices");
                });

            modelBuilder.Entity("MedicalAppointmentSystem.Domain.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("MedicalAppointmentSystem.Domain.Models.Hospital", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("MedicalAppointmentSystem.Domain.Models.MedicalService", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("MedicalAppointmentSystem.Domain.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
